[versions]
archunit = "1.2.1"
awaitility = "4.2.0"
bouncycastle = "1.77"
commons-text = "1.11.0"
kotlin_lang = "1.9.22"
kotlin-logging = "3.0.5"
logcaptor = "2.9.2"
mapstruct = "1.5.5.Final"
restdocs-apispec = "0.19.0"
semver4j = "0.16.4"
spock_bom = "2.4-M1-groovy-4.0"
spock-reports = "2.5.1-groovy-4.0"
testcontainers = "1.19.3"
